import type {Metadata} from "next";
import {Noto_Sans} from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import {Footer, Header, Sidebar, Up} from "@/components";

const notoSans = Noto_Sans({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Наш проект",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={notoSans.className}>
      <body>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar}></Sidebar>
          <div className={styles.body}>{children}</div>
          <Footer className={styles.footer} />
          <Up></Up>
        </div>
      </body>
    </html>
  );
}
